import { Html, Head, Main, NextScript } from "next/document";

export default function Document() {
	return (
		<Html lang="en">
			<Head>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
				<link
					rel="stylesheet"
					href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200&display=optional"
				/>
				<script
					src="https://kit.fontawesome.com/fa6782d3c9.js"
					crossOrigin="anonymous"
					defer
				></script>
			</Head>

			<body>
				<Main />
				<NextScript />
			</body>
		</Html>
	);
}
