import React from "react";
import styles from "./bodyTemplate.module.css";
import Head from "next/head";
import { Header, Footer } from "../containers";

const BodyTemplate = (props) => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200" />
      </Head>
      
      <Header></Header>
      body template
      <main>{props.child}</main>
      <Footer></Footer>
    </>
  );
};

export default BodyTemplate;
